/* generated by clorn (reborn revision 26015) — target: ISO C23 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef struct {
    int x;
    int y;
} Point;
typedef enum {
    Red,
    Green = 10,
    Blue
} Color;
int add(int a, int b)
{
    return (a + b);
}

void greet(char* name)
{
    printf("Hello, %s\n", name);
    return;
}

int main(void)
{
    printf("=== main() ===\n\n");
    int x = 0;
    int y = 0;
    printf("insert a number: ");
    char* line = NULL;
    size_t size = 0;
    ssize_t read = getline(&(line), &(size), stdin);
    if ((read == -(1)))
    {
        printf("getline() error while parsing input\n");
    }
    x = atoi(line);
    printf("insert a second number: ");
    if (read = (getline(&(line), &(size), stdin) == -(1)))
    {
        printf("getline() error while parsing input\n");
    }
    y = atoi(line);
    free(line);
    line = NULL;
    size = 0;
    read = 0;
    auto sum = add(x, y);
    printf("sum: %d\n", sum);
    if ((sum > 25))
    {
        printf("big number\n");
    }
    else if ((sum == 30))
    {
        printf("exactly 30\n");
    }
    else
    {
        printf("small number\n");
    }
    int i = 0;
    while ((i < 3))
    {
        printf("i = %d\n", i);
        i++;
    }
    for (int j = 0; (j < 3); j++)
    {
        printf("j = %d\n", j);
    }
    for (int _i = 0; _i < 5; _i++)
    {
        printf("%d range loop iter\n", _i);
    }
    char letter = 'a';
    auto code = ((int)(letter));
    printf("ascii of a: %d\n", code);
    Point p;
    p.x = 4;
    p.y = 8;
    printf("point: %d %d\n", p.x, p.y);
    int end_of_test = 1;
    if ((end_of_test == 1))
    {
        printf("end of test.\n");
        return 0;
    }
    else
    {
        return 1;
    }
}

